#:schema node_modules/wrangler/config-schema.json
name = "sublink-20260420"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "58accde7bf3e467f9e6b8508aeae6bb8" }
]

[assets]
directory = "./public"
